CMS_HOST: studio.academy.dynage.technology
CMS_OAUTH2_SECRET: IYjE1psLbmiCzlZl8zZ6dQSf
CONTACT_EMAIL: hello@dynage.technology
ENABLE_HTTPS: true
ID: fl4LdkB12dCiWv4zGypGNZ13
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAxnzbwHd8Q38l0xUwHvATzveobYo2NitWToT6Xw/VZYWrEH3P

  gNhhGod7K9LyGK6m0H4wVrs4eADr86t8YYz2HElHwD4yt1cdDZ7o90bKiH8j+vY6

  jaIEsY9Di0HZ6di6cgHbv+SNvqvgmTtYHK7W2U7+cae2qn3QZ/AyTjzwV0bMrLzI

  hThzVQoX+Y+WC+c7emlWAoJ/kJlHnoDvN77N1SPfi4LqYaLvnzlzZN7fc0buFWrG

  V0fK66vb97LdDf9cBXHk3KgePxuQCRr9prOW0Xt3VNUJy5YkXNYHG5ilSvi0eaHT

  PHhwzDZLqDQzJ53TscY28vma7gJ01AcKioXBKwIDAQABAoIBAB+XFqiCu9HIRj5a

  pG6AGj759qH8edVUP2e+zVRc4kNGq2u0AlcI2SeOQYG/kI1yGpWbR9k98eZTizoc

  ZG7oLvFgjl1f6NV6NWMKFBzq9OgViCX0k2wgSavy17ats99+gWoMtqtLVm3u0A/D

  PKpP/1zVsDRpk25+GLG6Ll96XmwdTcC+A83WAD4PjVNoOvJvXaHwKuEnC0H8yIp7

  gksreLrSSD/+4VezgFmbilWHcbjVvUIWet7ZkFOujW009Al7Q1XLwz4GSmOScckq

  nm0BujpLdunDhZjj/ktNz3n3VuadRGP8ptCEEg1tVjGkXScR0wLDNeaRARTF+QG7

  g1Lw7s0CgYEAx03SKvsYABJlVVWBR+x0DEa+zIQdMQaNC1u6/SpnVnXq4dF6IJlL

  TjevzUQAOSL46EBpirL9QKXpBcE7ICsnqTtMhTPuN1o7ibdnsDlbdDoSBnxypmw+

  HuiuNYd8s8yLM9T3HDbG85MDZ8V9plXmoTZHPxoKt5ye/FQH3DFzgM8CgYEA/vOY

  BpOkYaL7RC6T1k9ma48SGjsJyWDTfYcKG6k8IJ243EqwodxZWOaKTP9P4wPUFr8n

  xGO4FdUiZNQApbG2KhGzLBk+n12bswdDOQQlwQfm4IZAXLYHZ2lUTxlY+UmbMKAg

  EvhR6lsSSALNWx7U4Wawo9c982+mNanLMlyl+OUCgYADSAW4zW+EuMjQUdsSCxOS

  DCwiA97TKs9xq231sxgGdWSLmT5QgRWbURFk6MS0LB46/KyAKxg+Uzz16kuF6Q/7

  Gk3VN5ipcqPeTZW4cglObZJUZwIgOVIAgkYz/WoRL8Hu9YeoAELgScBZmgfKkEl+

  x/z+Tfh1M2/uqZeDiZDkQwKBgC3regpVNVpQnKkfKomDK5Nb5YrL72tSAUWuuOda

  h/Xn8o/a9A1zPrSAcZCEu8LLwbuHGoaI33MvPE6k0KkHZSQWpArhUSIrHgwU1srC

  MHqgDbmK9LS+JH8/vWuxyRC9bTJI5P4Fs9teI+DMgGhVGUqv0EjyT7o09d7cgjjD

  7zDxAoGAVTgjJCSST0KL0V7sOpNkggTwy68pNY+5td+YDJHSCY7LcMlPZv6kLJxZ

  9FD3LpPNo6TGzyZmGSg7GJRXwwANbwD/RsZkH41TBP5GWSRp0TWfJQZrDRdk1w1A

  VkQlKvv0WoGxApCSqgvrcmzOwyx5Z8uSB+o/y49e2vK3/LG3NMU=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: academy.dynage.technology
MEILISEARCH_API_KEY: 17c749654d56242be97a875504107bfd3b4912e990a7ca2f9a250a059121b8c6
MEILISEARCH_API_KEY_UID: 2511be9c-e453-489e-80aa-288eeb29380f
MEILISEARCH_MASTER_KEY: qvADb4s2ZLmO1y7ZelKypsxN
MYSQL_ROOT_PASSWORD: OE9FKbYO
OPENEDX_MYSQL_PASSWORD: SnnwdXuT
OPENEDX_SECRET_KEY: rFsHykgGTlBnvP90bQfH0Nze
PLATFORM_NAME: Dynage Academy
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
