name: Marketplace Develop CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'dynage-marketplace/**'
      - 'dynage-marketplace-storefront/**'
  pull_request:
    branches: [develop, main]
    paths:
      - 'dynage-marketplace/**'
      - 'dynage-marketplace-storefront/**'

jobs:
    admin-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run build

    storefront-test:
        runs-on: ubuntu-latest
        steps:
            # - name: Checkout code
            #   uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2

    #         - name: Deploy to production server
    #           env:
    #               NODE_ENV: production
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #           run: |
    #               echo "Deploying to production server..."